language: php

php:
  - 5.5
  - 5.6
  - hhvm
    - 7.0
    - 7.1
    - 7.2
    - 7.1
    - 7.2
matrix:
    include:
        - php: 7.1
          env: DEPENDENCIES=dev
        - php: 7.2
          env: DEPENDENCIES=dev
        - php: 5.5
        env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

install: composer install

